root -b -l -q print_yield.C\(\"bosons\"\)
root -b -l -q print_yield.C\(\"ttz\"\)
root -b -l -q print_yield.C\(\"ttw\"\)
root -b -l -q print_yield.C\(\"raretop\"\)
root -b -l -q print_yield.C\(\"tt1lpowheg\"\)
root -b -l -q print_yield.C\(\"tt2lpowheg\"\)
