name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  build:
    
    runs-on: ubuntu-latest
    container:
        image: rootproject/root:6.22.00-ubuntu20.04

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: apt install git && git submodule update --init --recursive
    - run: . rooutil/thisrooutil.sh && export VBSHWWNANOLOOPERDIR=$PWD && export LD_LIBRARY_PATH=$PWD/VBSHWWCORE:$LD_LIBRARY_PATH && export LD_LIBRARY_PATH=$PWD/NanoTools/NanoCORE:$LD_LIBRARY_PATH && make -j
